PARAMS = {
    'figsize' : (10, 10),
    'dpi' : 100,
    'xmin' : 0,
    'xmax' : 1,
    'ymin' : 0,
    'ymax' : 1,
    'fps' : 20,
    'image_dir' : '.',
    'video_dir' : '.',
    'frames_dir' : 'frames',
    'copyright' : {
        'text' : '@B.Corsini',
        'fname' : '@BC.otf',
        'ratio' : 0.05,
        'margin' : 0.02,
        'lw' : 2,
        'ec' : 'grey',
        'fc' : 'black',
        'params' : {
            'zorder' : 1000,
            'alpha' : 0.05,
            'joinstyle' : 'round',
            'capstyle' : 'round',
        },
    },
}